import { IconName, iconNames } from 'lucide-react/dynamic';
import { z } from 'zod';

// Zod schema for category validation
export const categorySchema = z.object({
  icon: z.enum(iconNames as [IconName, ...IconName[]]),
  title: z.string().min(1).max(50),
  description: z.string().min(1).max(200),
  slug: z.string().min(1).max(50),
  options: z.array(z.string()).optional(),
});

export type Category = z.infer<typeof categorySchema>;

export const categories: Category[] = [
  {
    icon: 'music',
    title: 'Music',
    description: 'Music that makes you feel something. Made by Someone, and not a team of analysts.',
    slug: 'music',
    options: [
      'rock',
      'jazz',
      'classical',
      'folk',
      'blues',
      'metal',
      'punk',

      'electronic',
      'indie-electronic',
      'synthpop',
      'lo-fi',
      'ambient',
      'experimental',
      'downtempo',
      'drum-and-bass',
      'dubstep',
      'house',
      'techno',
      'trance',
      'hardstyle',
      'hardcore',

      'rap',
      'underground-hip-hop',
      'alternative-hip-hop',
      'instrumental-hip-hop',
      'trip-hop',
      'trap',
      'dark-trap',
      'drill',
      'melodic-rap',
      'conscious-rap',

      'indie-rock',
      'post-rock',
      'art-rock',
      'noise-rock',
      'psychedelic',
      'garage-rock',
      'post-punk',
      'shoegaze',

      'industrial',
      'darkwave',
      'post-metal',
      'math-rock',

      'indie-folk',
      'contemporary-folk',
      'folk-punk',
      'anti-folk',
      'freak-folk',
      'spoken-word',

      'nu-jazz',
      'free-jazz',
      'jazz-fusion',
      'spiritual-jazz',

      'neo-classical',
      'contemporary-classical',
      'minimal',
      'modern-composition',

      'afrobeat',
      'world-fusion',
      'latin-alternative',
      'global-bass',

      'indie-pop',
      'dream-pop',
      'bedroom-pop',
      'hyperpop',
      'art-pop',

      'glitch',
      'idm',
      'breakcore',
      'vaporwave',
      'future-garage',

      'alternative-r&b',
      'future-soul',
      'uk-garage',
      'grime',

      'post-hardcore',
      'black-metal',
      'doom',
      'sludge',
      'crust-punk',
    ],
  },
  {
    icon: 'drill',
    title: 'Crafts',
    description: 'People that bring something new and unique into the world. Handmade, and special.',
    slug: 'crafts',
    options: ['woodwork', 'metalwork', 'ceramics', 'jewelry', 'electronics'],
  },
  {
    icon: 'paintbrush',
    title: 'Graphic Art',
    description: 'Illustrations that show the soul of the creator, visualised with every stroke.',
    slug: 'graphic-art',
    options: ['painting', 'drawing', 'digital art', 'traditional art'],
  },
  {
    icon: 'shirt',
    title: 'Fiber Arts',
    description: 'Textile creations that blend art and functionality, woven with care.',
    slug: 'fiber-arts',
    options: ['knitting', 'weaving', 'quilting', 'dyeing', 'embroidery'],
  },
  {
    icon: 'camera',
    title: 'Photography',
    description: 'Capturing moments that tell a story, convey feelings, and evoke memories.',
    slug: 'photography',
    options: ['portrait', 'landscape', 'wildlife', 'macro', 'street'],
  },
  {
    icon: 'pencil',
    title: 'Words',
    description: 'Words that weave worlds. Written by people who pour their hearts onto the page.',
    slug: 'words',
    options: ['poetry', 'prose', 'essays', 'novels', 'short stories', 'thoughts', 'fiction'],
  },
  {
    icon: 'clapperboard',
    title: 'Movies',
    description: 'Dialogues, emotions, stories, angles, lighting, and more. All combined to create something truly unique and beautiful.',
    slug: 'movies',
    options: ['documentary', 'indie', 'animation', 'short film', 'feature'],
  },
  {
    icon: 'code',
    title: 'Digital Art',
    description: "Working with collaboration, with powerful GPU's, to create stunning experiences.",
    slug: 'digital-art',
    options: ['3D modeling', 'animation', 'concept art', 'digital painting', 'digital sculpture'],
  },
  {
    icon: 'glasses',
    title: 'Mixed Media',
    description: 'Combines multiple mediums, creating a rich and layered experience that defies traditional categorization.',
    slug: 'mixed-media',
    options: ['collage', 'assemblage', 'installation', 'performance'],
  },
  {
    icon: 'shell',
    title: 'Content Creation',
    description:
      'Do You love podcasts, history videos, documentaries, educational, science, entertainment? Then it might be a place for You.',
    slug: 'content-creation',
    options: ['podcasts', 'vlogs', 'tutorials', 'history', 'science', 'entertainment', 'games'],
  },
  {
    icon: 'sparkles',
    title: 'Other',
    description: 'Things so unique, they do not fit in any of the categories. Who knows what You will find here.',
    slug: 'other',
    options: [],
  },
  {
    icon: 'sparkles',
    title: 'All Categories',
    description: 'Look for everything. No matter the size nor the category. We have it all.',
    slug: 'all-categories',
    options: [],
  },
];
