import { MusicGem } from '../types/gems';

export const dummyGems: MusicGem[] = [
  {
    id: '1',
    type: 'music',
    title: 'Neon Dreams',
    description: 'A synthwave journey through midnight cities',
    category: 'music',
    artist: {
      name: 'Midnight Protocol',
      location: 'Tokyo, Japan',
      avatar: 'https://i.pravatar.cc/150?u=artist1',
    },
    source: 'bandcamp',
    sourceUrl: 'https://bandcamp.com',
    albumArt: 'https://picsum.photos/seed/gem1/300/300',
    duration: '5:23',
    releaseDate: '2024-01-15',
    genres: ['synthwave', 'electronic', 'ambient'],
    tags: ['electronic', 'synthwave', 'night', 'city'],
    createdAt: '2024-01-15T00:00:00Z',
    updatedAt: '2024-01-15T00:00:00Z',
    likes: 142,
    saves: 67,
  },
  {
    id: '2',
    type: 'music',
    title: 'Underground Echoes',
    description: 'Raw basement recordings with pure punk energy',
    category: 'music',
    artist: {
      name: 'Concrete Youth',
      location: 'Berlin, Germany',
      avatar: 'https://i.pravatar.cc/150?u=artist2',
    },
    source: 'soundcloud',
    sourceUrl: 'https://soundcloud.com',
    albumArt: 'https://picsum.photos/seed/gem2/300/300',
    duration: '2:47',
    releaseDate: '2024-02-01',
    genres: ['punk', 'hardcore', 'underground'],
    tags: ['punk', 'diy', 'raw', 'basement'],
    createdAt: '2024-02-01T00:00:00Z',
    updatedAt: '2024-02-01T00:00:00Z',
    likes: 89,
    saves: 34,
  },
  {
    id: '3',
    type: 'music',
    title: 'Quantum Frequencies',
    description: 'Experimental electronic soundscapes',
    category: 'music',
    artist: {
      name: 'Data Horizon',
      location: 'Stockholm, Sweden',
      avatar: 'https://i.pravatar.cc/150?u=artist3',
    },
    source: 'youtube',
    sourceUrl: 'https://youtube.com',
    albumArt: 'https://picsum.photos/seed/gem3/300/300',
    duration: '7:15',
    releaseDate: '2024-01-28',
    genres: ['experimental', 'electronic', 'ambient'],
    tags: ['experimental', 'electronic', 'soundscape'],
    createdAt: '2024-01-28T00:00:00Z',
    updatedAt: '2024-01-28T00:00:00Z',
    likes: 234,
    saves: 112,
  },
  {
    id: '4',
    type: 'music',
    title: 'Bedroom Tapes Vol. 1',
    description: 'Lo-fi indie folk recordings',
    category: 'music',
    artist: {
      name: 'Autumn Leaves',
      location: 'Portland, USA',
    },
    source: 'bandcamp',
    sourceUrl: 'https://bandcamp.com',
    duration: '4:18',
    releaseDate: '2024-02-10',
    genres: ['indie-folk', 'lo-fi', 'acoustic'],
    tags: ['folk', 'acoustic', 'lo-fi', 'indie'],
    createdAt: '2024-02-10T00:00:00Z',
    updatedAt: '2024-02-10T00:00:00Z',
    likes: 67,
    saves: 28,
  },
  {
    id: '5',
    type: 'music',
    title: 'Neural Beats',
    description: 'AI-assisted underground hip-hop',
    category: 'music',
    artist: {
      name: 'Circuit Break',
      location: 'Seoul, South Korea',
      avatar: 'https://i.pravatar.cc/150?u=artist5',
    },
    source: 'spotify',
    sourceUrl: 'https://spotify.com',
    albumArt: 'https://picsum.photos/seed/gem5/300/300',
    duration: '3:45',
    releaseDate: '2024-02-15',
    genres: ['hip-hop', 'electronic', 'experimental'],
    tags: ['hip-hop', 'electronic', 'ai', 'experimental'],
    createdAt: '2024-02-15T00:00:00Z',
    updatedAt: '2024-02-15T00:00:00Z',
    likes: 312,
    saves: 145,
  },
]; 