import { FilterOptionsGroup, FilterSelectProps } from '@/features/shared/components/FilterSelect';
import {
  AU,
  BR,
  CA,
  CN,
  DE,
  DK,
  ES,
  FI,
  FR,
  GB,
  GR,
  ID,
  IL,
  IN,
  IT,
  JP,
  KR,
  MX,
  NL,
  NO,
  PH,
  PL,
  PT,
  RU,
  SA,
  SE,
  TH,
  TR,
  UA,
  VN,
} from 'country-flag-icons/react/3x2';

export const languageFlags = {
  en: GB,
  es: ES,
  ja: JP,
  ko: KR,
  fr: FR,
  de: DE,
  it: IT,
  pt: PT,
  'pt-br': BR,
  zh: CN,
  ru: RU,
  hi: IN,
  ar: SA,
  th: TH,
  vi: VN,
  id: ID,
  tl: PH,
  tr: TR,
  pl: PL,
  uk: UA,
  nl: NL,
  'es-mx': MX,
  'en-ca': CA,
  'en-au': AU,
  sv: SE,
  no: NO,
  da: DK,
  fi: FI,
  el: GR,
  he: IL,
} as const;

export const languages = [
  { id: 'en', label: 'English', Icon: languageFlags.en },
  { id: 'es', label: 'Español', Icon: languageFlags.es },
  { id: 'ja', label: '日本語', Icon: languageFlags.ja },
  { id: 'ko', label: '한국어', Icon: languageFlags.ko },
  { id: 'fr', label: 'Français', Icon: languageFlags.fr },
  { id: 'de', label: 'Deutsch', Icon: languageFlags.de },
  { id: 'it', label: 'Italiano', Icon: languageFlags.it },
  { id: 'pt', label: 'Português', Icon: languageFlags.pt },
  { id: 'pt-br', label: 'Português (Brasil)', Icon: languageFlags['pt-br'] },
  { id: 'zh', label: '中文', Icon: languageFlags.zh },
  { id: 'ru', label: 'Русский', Icon: languageFlags.ru },
  { id: 'hi', label: 'हिन्दी', Icon: languageFlags.hi },
  { id: 'ar', label: 'العربية', Icon: languageFlags.ar },
  { id: 'th', label: 'ไทย', Icon: languageFlags.th },
  { id: 'vi', label: 'Tiếng Việt', Icon: languageFlags.vi },
  { id: 'id', label: 'Bahasa Indonesia', Icon: languageFlags.id },
  { id: 'tl', label: 'Tagalog', Icon: languageFlags.tl },
  { id: 'tr', label: 'Türkçe', Icon: languageFlags.tr },
  { id: 'pl', label: 'Polski', Icon: languageFlags.pl },
  { id: 'uk', label: 'Українська', Icon: languageFlags.uk },
  { id: 'nl', label: 'Nederlands', Icon: languageFlags.nl },
  { id: 'es-mx', label: 'Español (México)', Icon: languageFlags['es-mx'] },
  { id: 'en-ca', label: 'English (Canada)', Icon: languageFlags['en-ca'] },
  { id: 'en-au', label: 'English (Australia)', Icon: languageFlags['en-au'] },
  { id: 'sv', label: 'Svenska', Icon: languageFlags.sv },
  { id: 'no', label: 'Norsk', Icon: languageFlags.no },
  { id: 'da', label: 'Dansk', Icon: languageFlags.da },
  { id: 'fi', label: 'Suomi', Icon: languageFlags.fi },
  { id: 'el', label: 'Ελληνικά', Icon: languageFlags.el },
  { id: 'he', label: 'עברית', Icon: languageFlags.he },
].sort((a, b) => a.label.localeCompare(b.label));

export type FilterOption = {
  id: string;
  label: string;
  description?: string;
};

export const audienceSizes = [
  {
    id: 'microscopic',
    label: 'Microscopic',
    description: 'Less than 100 followers',
  },
  { id: 'tiny', label: 'Tiny', description: '100 - 1k followers' },
  { id: 'little', label: 'Little', description: '1k - 10k followers' },
  { id: 'small', label: 'Small', description: '10k - 50k followers' },
  {
    id: 'substantial',
    label: 'Substantial',
    description: '50k - 100k followers',
  },
  { id: 'giant', label: 'Giant', description: 'More than 100k followers' },
] as FilterOption[];

export const musicGenres: FilterOptionsGroup[] = [
  {
    id: 'electronic',
    name: 'Electronic',
    options: [
      {
        id: 'electronic',
        label: 'Electronic',
        description: 'Electronic music',
      },
      {
        id: 'indie-electronic',
        label: 'Indie Electronic',
        description: 'Electronic with indie elements',
      },
      { id: 'synthpop', label: 'Synthpop', description: 'Synthetic pop music' },
      { id: 'lo-fi', label: 'Lo-Fi', description: 'Low fidelity production' },
      {
        id: 'ambient',
        label: 'Ambient',
        description: 'Atmospheric electronic',
      },
      {
        id: 'experimental',
        label: 'Experimental',
        description: 'Pushing boundaries',
      },
      {
        id: 'downtempo',
        label: 'Downtempo',
        description: 'Slow tempo electronic',
      },
      {
        id: 'drum-and-bass',
        label: 'Drum & Bass',
        description: 'Fast breakbeat',
      },
      { id: 'dubstep', label: 'Dubstep', description: 'Bass-heavy electronic' },
      { id: 'house', label: 'House', description: 'Four-on-the-floor beats' },
      { id: 'techno', label: 'Techno', description: 'Repetitive electronic' },
      { id: 'trance', label: 'Trance', description: 'Hypnotic electronic' },
      {
        id: 'hardstyle',
        label: 'Hardstyle',
        description: 'Hard-hitting electronic',
      },
      { id: 'french-core', label: 'French Core', description: 'French electronic' },
      { id: 'hardcore', label: 'Hardcore', description: 'Extreme electronic' },
    ],
  },
  {
    name: 'Hip-Hop & Rap',
    id: 'hip-hop-and-rap',
    options: [
      { id: 'rap', label: 'Rap', description: 'Rhythmic poetry' },
      {
        id: 'underground-hip-hop',
        label: 'Underground Hip-Hop',
        description: 'Alternative rap',
      },
      {
        id: 'alternative-hip-hop',
        label: 'Alternative Hip-Hop',
        description: 'Non-mainstream rap',
      },
      {
        id: 'instrumental-hip-hop',
        label: 'Instrumental Hip-Hop',
        description: 'Beat-focused',
      },
      { id: 'trip-hop', label: 'Trip-Hop', description: 'Downtempo hip-hop' },
      { id: 'trap', label: 'Trap', description: 'Modern rap style' },
      { id: 'dark-trap', label: 'Dark Trap', description: 'Atmospheric trap' },
      { id: 'drill', label: 'Drill', description: 'Raw trap style' },
      { id: 'melodic-rap', label: 'Melodic Rap', description: 'Singing rap' },
      {
        id: 'conscious-rap',
        label: 'Conscious Rap',
        description: 'Thoughtful lyrics',
      },
    ],
  },
  {
    name: 'Rock & Metal',
    id: 'rock-and-metal',
    options: [
      {
        id: 'indie-rock',
        label: 'Indie Rock',
        description: 'Independent rock',
      },
      { id: 'post-rock', label: 'Post-Rock', description: 'Atmospheric rock' },
      { id: 'art-rock', label: 'Art Rock', description: 'Experimental rock' },
      { id: 'noise-rock', label: 'Noise Rock', description: 'Dissonant rock' },
      {
        id: 'psychedelic',
        label: 'Psychedelic',
        description: 'Mind-expanding',
      },
      { id: 'garage-rock', label: 'Garage Rock', description: 'Raw rock' },
      { id: 'post-punk', label: 'Post-Punk', description: 'Experimental punk' },
      { id: 'shoegaze', label: 'Shoegaze', description: 'Wall of sound' },
      {
        id: 'industrial',
        label: 'Industrial',
        description: 'Mechanical sounds',
      },
      {
        id: 'post-metal',
        label: 'Post-Metal',
        description: 'Atmospheric metal',
      },
      { id: 'math-rock', label: 'Math Rock', description: 'Complex rhythms' },
    ],
  },
  {
    name: 'Folk & Acoustic',
    id: 'folk-and-acoustic',
    options: [
      { id: 'indie-folk', label: 'Indie Folk', description: 'Modern folk' },
      {
        id: 'contemporary-folk',
        label: 'Contemporary Folk',
        description: 'Modern traditional',
      },
      { id: 'folk-punk', label: 'Folk Punk', description: 'Energetic folk' },
      { id: 'anti-folk', label: 'Anti-Folk', description: 'Subversive folk' },
      {
        id: 'freak-folk',
        label: 'Freak Folk',
        description: 'Experimental folk',
      },
      { id: 'spoken-word', label: 'Spoken Word', description: 'Poetic speech' },
    ],
  },
  {
    name: 'Jazz & Classical',
    id: 'jazz-and-classical',
    options: [
      { id: 'nu-jazz', label: 'Nu Jazz', description: 'Modern jazz' },
      { id: 'free-jazz', label: 'Free Jazz', description: 'Experimental jazz' },
      { id: 'jazz-fusion', label: 'Jazz Fusion', description: 'Mixed jazz' },
      {
        id: 'spiritual-jazz',
        label: 'Spiritual Jazz',
        description: 'Meditative jazz',
      },
      {
        id: 'neo-classical',
        label: 'Neo-Classical',
        description: 'Modern classical',
      },
      {
        id: 'contemporary-classical',
        label: 'Contemporary Classical',
        description: 'New classical',
      },
      { id: 'minimal', label: 'Minimal', description: 'Minimalist music' },
    ],
  },
  {
    name: 'Pop & R&B',
    id: 'pop-and-rb',
    options: [
      { id: 'indie-pop', label: 'Indie Pop', description: 'Independent pop' },
      { id: 'dream-pop', label: 'Dream Pop', description: 'Ethereal pop' },
      { id: 'bedroom-pop', label: 'Bedroom Pop', description: 'DIY pop' },
      { id: 'hyperpop', label: 'Hyperpop', description: 'Exaggerated pop' },
      { id: 'art-pop', label: 'Art Pop', description: 'Experimental pop' },
      {
        id: 'alternative-r&b',
        label: 'Alternative R&B',
        description: 'Modern R&B',
      },
      { id: 'future-soul', label: 'Future Soul', description: 'Modern soul' },
    ],
  },
  {
    name: 'Other',
    id: 'other',
    options: [
      { id: 'glitch', label: 'Glitch', description: 'Error music' },
      { id: 'idm', label: 'IDM', description: 'Intelligent Dance Music' },
      { id: 'breakcore', label: 'Breakcore', description: 'Chaotic breaks' },
      {
        id: 'vaporwave',
        label: 'Vaporwave',
        description: 'Nostalgic electronic',
      },
      {
        id: 'future-garage',
        label: 'Future Garage',
        description: 'Modern garage',
      },
      { id: 'darkwave', label: 'Darkwave', description: 'Dark electronic' },
    ],
  },
] as const;

export const genderOptions: FilterOption[] = [
  { id: 'male', label: 'Male' },
  { id: 'female', label: 'Female' },
  { id: 'non-binary', label: 'Non-Binary' },
  { id: 'other', label: 'Other' },
  { id: 'group', label: 'Group', description: 'A group of artists' },
] as const;

export const platformOptions: FilterOption[] = [
  { id: 'youtube', label: 'YouTube' },
  { id: 'tiktok', label: 'TikTok' },
  { id: 'soundcloud', label: 'SoundCloud' },
  { id: 'streaming-platforms', label: 'Streaming Platforms' },
  { id: 'bandcamp', label: 'Bandcamp' },
  { id: 'instagram', label: 'Instagram' },
] as const;

export const bpmOptions: FilterOption[] = [
  { id: '60-90', label: '30-90 BPM', description: 'Downbeat' },
  { id: '90-120', label: '90-120 BPM', description: 'Mid tempo' },
  { id: '120-160', label: '120-160 BPM', description: 'Danceable' },
  { id: '160+', label: '160+ BPM', description: 'High energy' },
] as const;

export const moodOptions: FilterOption[] = [
  { id: 'euphoric', label: 'Euphoric', description: 'Transcendent waves of joy' },
  { id: 'melancholic', label: 'Melancholic', description: 'Beautiful shades of sadness' },
  { id: 'ethereal', label: 'Ethereal', description: 'Dreamy and otherworldly' },
  { id: 'nostalgic', label: 'Nostalgic', description: 'Bittersweet memories and longing' },
  { id: 'cathartic', label: 'Cathartic', description: 'Raw emotional release' },
  { id: 'ecstatic', label: 'Ecstatic', description: 'Pure uninhibited bliss' },
  { id: 'energetic', label: 'Energetic', description: 'High-powered and dynamic' },
  { id: 'dark', label: 'Dark', description: 'Brooding and mysterious' },
  { id: 'peaceful', label: 'Peaceful', description: 'Calming and serene' },
  { id: 'aggressive', label: 'Aggressive', description: 'Intense and powerful' },
  { id: 'playful', label: 'Playful', description: 'Fun and lighthearted' },
  { id: 'atmospheric', label: 'Atmospheric', description: 'Immersive soundscapes' },
  { id: 'hypnotic', label: 'Hypnotic', description: 'Mesmerizing and trance-like' },
  { id: 'uplifting', label: 'Uplifting', description: 'Inspiring and motivational' },
] as const;

export const lyricsOptions: FilterOption[] = [
  { id: 'no-lyrics', label: 'No Lyrics', description: 'Instrumental tracks' },
  { id: 'social-issues', label: 'Social Issues', description: 'Lyrics addressing social topics' },
  { id: 'storytelling', label: 'Storytelling', description: 'Lyrics that tell a narrative or story' },
  { id: 'existential', label: 'Existential', description: 'Deep philosophical lyrics' },
  { id: 'surreal', label: 'Surreal', description: 'Abstract and dream-like lyrics' },
  { id: 'nature', label: 'Nature', description: 'Lyrics about the natural world and environment' },
  { id: 'urban', label: 'Urban', description: 'City life and modern experiences' },
  { id: 'nostalgia', label: 'Nostalgia', description: 'Reminiscing about the past' },
  { id: 'spiritual', label: 'Spiritual', description: 'Mystical and religious themes' },
  { id: 'sci-fi', label: 'Sci-Fi', description: 'Futuristic and technological themes' },
  { id: 'mythological', label: 'Mythological', description: 'Ancient myths and legends' },
  { id: 'meme', label: 'Meme', description: 'Irony and sarcasm' },
  { id: 'party', label: 'Party', description: 'Lyrics suitable for celebrations and gatherings' },
  { id: 'love', label: 'Love', description: 'Lyrics about love and relationships' },
  { id: 'personal-growth', label: 'Personal Growth', description: 'Lyrics about self-improvement and introspection' },
] as const;

export const additionalOptions: FilterOption[] = [
  {
    id: 'has-music-video',
    label: 'Has Music Video',
    description: 'Track with a music video',
  },
  {
    id: 'has-lyrics',
    label: 'Has Lyrics',
    description: 'Lyrics of this track are available on the page',
  },
] as const;

export const musicFilters: Omit<FilterSelectProps, 'selectedValues' | 'onSelectionChange'>[] = [
  {
    title: 'Gender',
    options: genderOptions,
    param: 'gender',
    icon: 'User',
    isSearchable: false,
    showFilterChips: false,
  },
  {
    title: 'Genre',
    options: musicGenres,
    param: 'genre',
    icon: 'Music',
    isSearchable: true,
    showFilterChips: true,
  },
  {
    title: 'Audience Size',
    options: audienceSizes,
    param: 'audience-size',
    icon: 'Users',
    isSearchable: false,
    showFilterChips: false,
  },
  {
    title: 'Platform',
    options: platformOptions,
    param: 'platform',
    icon: 'Globe',
    isSearchable: false,
    showFilterChips: false,
  },
  {
    title: 'BPM',
    options: bpmOptions,
    param: 'bpm',
    icon: 'AudioLines',
    isSearchable: false,
    showFilterChips: false,
  },
  {
    title: 'Mood',
    options: moodOptions,
    param: 'mood',
    icon: 'Smile',
    isSearchable: true,
    showFilterChips: true,
  },
  {
    title: 'Lyrics',
    options: lyricsOptions,
    param: 'lyrics',
    icon: 'ScrollText',
    isSearchable: false,
    showFilterChips: false,
  },
  {
    title: 'Additional',
    options: additionalOptions,
    param: 'additional',
    icon: 'Plus',
    isSearchable: false,
    showFilterChips: false,
  },
];
